package com.company.openplatform.application.api;
import com.company.openplatform.application.application.ApplicationService; import com.company.openplatform.identity.application.AccountPrincipal; import com.company.openplatform.shared.observability.RequestIdFilter; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import java.util.List; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/console/api/v1/applications") public class ApplicationController {
 private final ApplicationService service; public ApplicationController(ApplicationService service){this.service=service;}
 @PostMapping public ResponseEntity<ApplicationCreatedResponse> create(@Valid @RequestBody ApplicationRequest body,Authentication auth,HttpServletRequest request){var result=service.create(principal(auth).accountId(),body.name(),body.purpose());var v=result.application();return ResponseEntity.status(201).cacheControl(CacheControl.noStore()).body(new ApplicationCreatedResponse(v.applicationId(),v.name(),v.purpose(),v.appId(),result.appSecret(),v.environment(),v.status(),true,v.createdAt(),v.updatedAt(),id(request)));}
 @GetMapping public ResponseEntity<List<ApplicationResponse>> list(Authentication auth,HttpServletRequest request){String requestId=id(request);var body=service.list(principal(auth).accountId()).stream().map(v->new ApplicationResponse(v.applicationId(),v.name(),v.purpose(),v.appId(),v.environment(),v.status(),v.createdAt(),v.updatedAt(),requestId)).toList();return ResponseEntity.ok().header(RequestIdFilter.HEADER,requestId).body(body);}
 private AccountPrincipal principal(Authentication a){if(a!=null&&a.getPrincipal() instanceof AccountPrincipal p)return p;throw new IllegalStateException("authenticated principal missing");}
 private String id(HttpServletRequest r){return (String)r.getAttribute(RequestIdFilter.ATTRIBUTE);}
}
