package com.company.openplatform.permission.api;
import com.company.openplatform.identity.application.AccountPrincipal; import com.company.openplatform.permission.application.PermissionService; import com.company.openplatform.shared.observability.RequestIdFilter; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import java.util.List; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/console/api/v1/applications/{applicationId}/permissions") public class PermissionController {
 private final PermissionService service; public PermissionController(PermissionService service){this.service=service;}
 @GetMapping public ResponseEntity<List<PermissionResponse>> list(@PathVariable String applicationId,Authentication auth,HttpServletRequest request){validateApplicationId(applicationId);String id=id(request);return ResponseEntity.ok().header(RequestIdFilter.HEADER,id).body(map(service.list(principal(auth),applicationId),id));}
 @PostMapping public ResponseEntity<List<PermissionResponse>> submit(@PathVariable String applicationId,@Valid @RequestBody PermissionRequest body,Authentication auth,HttpServletRequest request){validateApplicationId(applicationId);String id=id(request);return ResponseEntity.ok().header(RequestIdFilter.HEADER,id).body(map(service.submit(principal(auth),applicationId,body.permissions(),body.reason()),id));}
 private List<PermissionResponse> map(List<PermissionService.View> views,String id){return views.stream().map(v->new PermissionResponse(v.code(),v.name(),v.purpose(),v.dataScope(),v.sensitiveNotice(),v.status(),v.submittedAt(),v.updatedAt(),v.rejectionReason(),id)).toList();}
 private void validateApplicationId(String value){try{if(!java.util.UUID.fromString(value).toString().equalsIgnoreCase(value))throw new IllegalArgumentException("applicationId invalid");}catch(IllegalArgumentException invalid){throw new IllegalArgumentException("applicationId invalid",invalid);}}
 private String principal(Authentication a){if(a!=null&&a.getPrincipal() instanceof AccountPrincipal p)return p.accountId();throw new IllegalStateException("authenticated principal missing");} private String id(HttpServletRequest r){return (String)r.getAttribute(RequestIdFilter.ATTRIBUTE);}
}
